package com.ptstore.models;
// Generated Dec 23, 2020 3:53:44 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rate generated by hbm2java
 */
@Entity
@Table(name = "rate", catalog = "dbterm4")
public class Rate implements java.io.Serializable {

	private Integer id;
	private Product product;
	private int star1;
	private int star2;
	private int star3;
	private int star4;
	private int star5;

	public Rate() {
	}

	public Rate(Product product, int star1, int star2, int star3, int star4, int star5) {
		this.product = product;
		this.star1 = star1;
		this.star2 = star2;
		this.star3 = star3;
		this.star4 = star4;
		this.star5 = star5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "star1", nullable = false)
	public int getStar1() {
		return this.star1;
	}

	public void setStar1(int star1) {
		this.star1 = star1;
	}

	@Column(name = "star2", nullable = false)
	public int getStar2() {
		return this.star2;
	}

	public void setStar2(int star2) {
		this.star2 = star2;
	}

	@Column(name = "star3", nullable = false)
	public int getStar3() {
		return this.star3;
	}

	public void setStar3(int star3) {
		this.star3 = star3;
	}

	@Column(name = "star4", nullable = false)
	public int getStar4() {
		return this.star4;
	}

	public void setStar4(int star4) {
		this.star4 = star4;
	}

	@Column(name = "star5", nullable = false)
	public int getStar5() {
		return this.star5;
	}

	public void setStar5(int star5) {
		this.star5 = star5;
	}

}
